name: AntiRelog
version: '${version}'
main: ru.shirk.antirelog.AntiRelog
api-version: '1.16'
authors: [shirkqqe]
description: AntiRelog plugin
website: https://github.com/shirkqqe
softdepend:
  - TAB

commands:
  antirelog:
    aliases:
      - ar
    description: ""
